import './config';
import { app, BrowserWindow, ipcMain, MenuItem } from 'electron';
import { Databased } from './process/Databased';
import { WithId, Document as MongoDocument } from 'mongodb';
import { BlogPost } from './types/BlogPost';
import { IcpCommunicationMessages } from './types/IcpCommunication/IcpCommunicationMessages';
import { session, Menu } from "electron"
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

const iggnoreWords = new Set<string>();

const enableSpellChecking = () => {
  session.defaultSession.setSpellCheckerLanguages(['en-GB']);
  mainWindow?.webContents.on("context-menu", (event, params) => {
    const menu = new Menu();

    for (const suggestion of params.dictionarySuggestions) {
      menu.append(new MenuItem({
        label: suggestion,
        click: () => {
          mainWindow?.webContents.replaceMisspelling(suggestion);
        }
      }));
    }

    if (params.misspelledWord) {
      menu.append(new MenuItem({ type: "separator" }));
      menu.append(new MenuItem({
        label: "Add to dictionary",
        click: () => {
          mainWindow?.webContents.session.addWordToSpellCheckerDictionary(params.misspelledWord);
        }
      }));
      menu.append(new MenuItem({
        label: "Ignore word",
        click: () =>
        {
          iggnoreWords.add(params.misspelledWord);
          mainWindow?.webContents.session.addWordToSpellCheckerDictionary(params.misspelledWord);
        }
      }))
    }

    menu.popup();
  })
}


const removeIgnoreWordsFromDictionary = () =>
{
  for (const word of iggnoreWords)
  {
    mainWindow?.webContents.session.removeWordFromSpellCheckerDictionary(word);
  }
}

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1920,
    height: 1080,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      spellcheck: true
    },
    autoHideMenuBar: true,
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  //mainWindow.webContents.openDevTools();

  enableSpellChecking();

  mainWindow.on("close", () =>
  {
    removeIgnoreWordsFromDictionary();
  })
};


// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.handle("post-blog", async (event: Electron.IpcMainInvokeEvent, postData: BlogPost) => {
  try {
    mainWindow?.webContents.send(IcpCommunicationMessages.StartBlogPostUpload, postData.title);
    await database.makePost(postData);
    mainWindow?.webContents.send(IcpCommunicationMessages.FinishBlogPostUpload, postData.title);
  }
  catch (error) {
    console.error("Failed to make post in database");
    console.log(error);
    mainWindow?.webContents.send(IcpCommunicationMessages.FailBlogPostUpload, postData.title);
  }
});

const database: Databased = new Databased();

app.on("before-quit", async (event) => {
  database?.dispose();
});

async function retrieveDataFromDatabase(): Promise<void> {
  console.log(await database.getPosts());
}