import dotenv from 'dotenv';
import { app, BrowserWindow, ipcMain } from 'electron';
import { Databased } from './Process/Databased';
import { WithId, Document as MongoDocument} from 'mongodb';
import { BlogPost } from './types/BlogPost';
import { IcpCommunicationMessages } from './types/IcpCommunication/IcpCommunicationMessages';

dotenv.config({path: './production.env'});
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1920,
    height: 1080,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    autoHideMenuBar: true,
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  //mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.handle("post-blog", async (event: Electron.IpcMainInvokeEvent, postData: BlogPost) =>
{
  try{
    mainWindow.webContents.send(IcpCommunicationMessages.StartBlogPostUpload, postData.title);
    await database.makePost(postData);
    mainWindow.webContents.send(IcpCommunicationMessages.FinishBlogPostUpload, postData.title);
  }
  catch
  {
    console.error("Failed to make post in database");
    mainWindow.webContents.send(IcpCommunicationMessages.FailBlogPostUpload, postData.title);
  }
});

let database: Databased | undefined = undefined;

app.on("before-quit", async (event) =>
{
  database?.dispose();
});

async function RetrieveDataFromDatabase() : Promise<void>
{
  database = new Databased();
  await database.connect();  
  console.log(await database.getPosts());
}

RetrieveDataFromDatabase();